# Generated by Django 4.0.4 on 2022-04-28 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_private_token_user_public_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('public_token', models.UUIDField(default=False, editable=False, unique=True)),
                ('title', models.CharField(default='', max_length=70)),
                ('question', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
