# Generated by Django 4.0.4 on 2022-04-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_question_questionmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionManager',
        ),
        migrations.AlterField(
            model_name='question',
            name='public_token',
            field=models.UUIDField(default=False, editable=False),
        ),
    ]
